### ISSUE TITLE
Nothing is going on

### ISSUE THREAD

**Issue by xKarmaSs** [vudung45/ValorantSkillEnhancer#2]
Hi man i am using a arduino Micro on the right COM, and the programm compiled fine... now when i run the programm i get no errors and the debugger gives me no error erther you know how to fix the problem?

**Comment by vudung45** [comment]
How to make it works is a plain as day light! This repo was recreated for educational purposes. I have no intention to encourage cheating in game!

**Comment by xKarmaSs** [comment]
okay can i ask what board you have?
